- src/__tests__/__snapshots__/LinksContainer.test.js.snap
- src/js/static/links.js
Endret lenke til Din Pensjon igjen
Feil hos Din Pensjon ved dyplenking til din pensjonsopptjening.
> Tekstendringer

- package-lock.json
- package.json
- src/pages/forside/sections/6-eksterne/EksterneLenkerData.ts
- src/pages/forside/sections/7-informasjon/MerInformasjon.less
- src/pages/forside/sections/7-informasjon/MerInformasjon.tsx
- src/pages/forside/sections/7-informasjon/MerInformasjonPanel.tsx
- Ny lenke pensjon + oppdatert arbeidsforhold
- Tastaturnavigasjon på mer informasjon
- Ny versjon av arbeidsforhold
> Lenker og pensjon

- .env.sample
- .github/workflows/deploy.prod.yml
- .github/workflows/deploy.q0.yml
- .github/workflows/deploy.q1.yml
- .github/workflows/deploy.q2.yml
- .github/workflows/deploy.q6.yml
- src/__tests__/env.test.ts
- src/assets/img/Skjerming.svg
- src/pages/forside/sections/6-flere-opplysninger/Lenker.tsx
- src/text/nb.ts
Deploy til prod må ventes med, men q0 og resterende er det bare å deploy til med en gang om mulig. Hvis ikke, null stress.
> Lenke mot skjerming-app

- package-lock.json
- package.json
- src/App.tsx
- src/pages/forside/sections/4-personinfo/4-utbetalinger/Utbetalinger.tsx
Midlertidig feilmelding for visning av utenlandsk kontonummer
> Utenlandsk konto errormsg

- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
- CODEOWNERS
- README.md
- package.json
- endrer fra tagging til å trigge manuelt
- oppdatert CODEOWNERS
- oppdatert scripts for versiontagging + rutiner for deploy i readme
> Oppdaterer mekanisme og rutiner for deploy

- src/pages/forside/sections/6-flere-opplysninger/LenkerData.ts
- src/utils/redirects.ts
Din Pensjon / pselv har byttet url fra tjenester.nav.no/pselv til www.nav.no/pselv
> Oppdaterer pselv-lenker

- src/text/en.ts
- src/text/nb.ts
(spesifiserer at fengsel er inkludert)
> Oppdaterer tekst for institusjonsopphold

- .env.sample
- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
- src/pages/forside/sections/6-flere-opplysninger/LenkerData.ts
Denne lenken skal testes først i dev. og må endres før prodsetting.
Lenken som skal i prod: https://person.nav.no/mine-saker/
> Endret_lenke_til_Dine_saker_OBS_Lenken_må_endres_før_prodsetting

- src/pages/forside/sections/5-arbeidsforhold/Arbeidsforhold.tsx
Fikser en bug som fører til at tilbake-knapp går til redirect tilbake til locale-url
> Lenker til riktig locale-versjon av arbeidsforhold

- package-lock.json
- package.json
- src/__tests__/endre-personopplysninger/__snapshots__/EndreOpplysninger.test.tsx.snap
- src/__tests__/forside/__snapshots__/Adresser.test.tsx.snap
- src/pages/forside/sections/4-personinfo/3-adresser/visning/Adresse.tsx
Fikser datoformattering til dd.mm.yyyy
> Fikser datoformattering

- src/__tests__/forside/__snapshots__/DittNavKontor.test.tsx.snap
- src/clients/apiMock/app/fetch/person-info.json
- src/pages/forside/sections/4-personinfo/5-ditt-nav-kontor/apningstider/Apningstid.tsx
- src/pages/forside/sections/4-personinfo/5-ditt-nav-kontor/apningstider/Apningstider.less
- src/pages/forside/sections/4-personinfo/5-ditt-nav-kontor/apningstider/Apningstider.tsx
- src/pages/forside/sections/4-personinfo/5-ditt-nav-kontor/apningstider/FormaterApningstider.tsx
- src/text/en.ts
- src/text/nb.ts
- src/text/nn.ts
- src/types/enhetKontaktInfo.ts
- Henter åpningstider som liste fra backend (tar med spesielle/andre åpningstider som ikke kom med tidligere)
- Skilt FormaterApningstider-komponent ut i egen fil
> Apningstider list

- .github/workflows/deploy.dev.yml
Eks:
-   Endrer type i foobar-objektet.
-   Oppdaterer diverse destruct etter typeendringer.
Eks: Har testet selv i dev / q6
Eks: Sjekk om du er enig i hvordan objektet destructes med default-verdi.
> Bruker ny ingress for personopplysninger-api i dev

- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
- .nais/config.yaml
Legger inn externalHosts i accessPolicy.
> Legger til korrekte externalHosts

- .github/workflows/deploy.dev.yml
Appen tilretteleggingsbehov-innsyn har fått oppdatert sin URL i dev i henhold til retningslinjer fra NAIS
> Oppdater URL til tilretteleggingsbehov-innsyn i dev

- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
- src/clients/apiClient.ts
- src/utils/redirects.ts
Bruker wonderwall-login i stedet for loginservice
> Bruker wonderwall-login i stedet for loginservice

- package-lock.json
- package.json
Oppgradere arbeidsforhold til ny versjon
Testet i dev
> Oppgradere arbeidsforhold til ny versjon

- package-lock.json
- package.json
- server/dekorator.js
- src/index.tsx
Fjerner bruk av appBase i utloggingsvarsel og versjonsbumper nav-dekoratoren-moduler
Testes i dev
> Fjerner appBase og oppdaterer nav-dekoratoren-moduler

- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
- Dockerfile
- src/clients/apiClient.ts
Oppdaterer til Node20 og bytter til bulls-eye-slim-image.
Testes i dev
> Oppgraderer til Node 20

- server/server.js
- src/utils/redirects.ts
CodeQL har rapportert på 2 potensielle issues i forbindelse med sanitering av URL og regex som kan krasje siden:
https://github.com/navikt/personopplysninger/security/code-scanning/9
https://github.com/navikt/personopplysninger/security/code-scanning/8
Ikke superkritisk siden dette kun skjer frontend, så dette er like mye for å sjekke hvordan flyten i sikkerhetsrapportering oppfører seg.
Testet i dev
> Vaske og validere url

- package-lock.json
- package.json
Oppdaterer til siste versjon ar arbeidsforhold etter konvensjonsendringer som rapportert av SonarCloud.
Testet i dev
> Teste beta av arbeidsforhold

- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
Fjerner API-key fra deploy-config.
Testet i dev
> Fjerner NAIS_DEPLOY_APIKEY fra workflow

- package-lock.json
- package.json
> Bump arbeidsforhold

- src/__tests__/intitusjonsopphold/__snapshots__/InstHistorikk.test.tsx.snap
- src/text/en.ts
- src/text/nb.ts
- src/text/nn.ts
Korrigert tekst i informasjon om institusjonsopphold
Har testet selv i dev
> Endre tekst i informasjon om institusjonsopphold

- server/dekorator.js
Putter parametere inn i params-objekt. Usikker på når det sluttet å funke, men det var ihvertfall feil slik det var tidligere.
Testet i dev
> Justerer params for utloggingsvarsel

- src/clients/apiMock/app/fetch/person-info-utenlandskbank.json
- src/clients/apiMock/app/fetch/person-info.json
- src/pages/forside/sections/4-personinfo/1-personalia/Personalia.tsx
- src/text/en.ts
- src/text/nb.ts
- src/text/nn.ts
- src/types/adresser/adresse.ts
- src/types/adresser/bostedsadresse.ts
- src/types/adresser/deltbosted.ts
- src/types/adresser/kontaktadresse.ts
- src/types/adresser/oppholdsadresse.ts
- src/types/inst.ts
- src/types/personalia.ts
> Opprydning

- package-lock.json
- package.json
Oppdaterer til siste versjon av arbeidsforhold hvor less er migrert til scss
Testet i dev
> Teste arbeidsforhold endringer

- LICENSE.md
- README.md
- package-lock.json
- package.json
- server/package.json
- src/__tests__/digital-samhandling-offentlig-privat/__snapshots__/DsopHistorikk.test.tsx.snap
- src/__tests__/endre-personopplysninger/__snapshots__/EndreOpplysninger.test.tsx.snap
- src/__tests__/forside/__snapshots__/Adresser.test.tsx.snap
- src/__tests__/forside/__snapshots__/DittNavKontor.test.tsx.snap
- src/__tests__/forside/__snapshots__/Kontaktinfo.test.tsx.snap
- src/__tests__/intitusjonsopphold/__snapshots__/InstHistorikk.test.tsx.snap
- src/__tests__/medlemskap-i-folketrygden/__snapshots__/MedlHistorikk.test.tsx.snap
- src/clients/apiMock/app/fetch/medl-info.json
- src/clients/apiMock/app/fetch/person-info-utenlandskbank.json
- src/clients/apiMock/app/fetch/person-info.json
- src/text/en.ts
- src/text/en/information.ts
- src/text/nb.ts
- src/text/nb/informasjon.ts
- src/text/nn.ts
- src/text/nn/informasjon.ts
- Endrer NAV til Nav.
- Oppdaterer arbeidsforhold for å få inn tilsvarende endringer derfra.
Testes i dev
> Nav til nav

- .env.sample
- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
Lenke til dokumentarkivet fra "Flere opplysninger om deg", feiler.  Har oppdatert lenken.
Har testet i dev
> Fikse lenke til dokumentarkivet fra Flere opplysninger om deg

- package-lock.json
- package.json
- src/__tests__/forside/__snapshots__/DittNavKontor.test.tsx.snap
Oppdaterer versjon av nav-office-reception-info
> Oppdaterer versjon av nav-office-reception-info

- package-lock.json
- package.json
- src/clients/apiMock/index.ts
fetch-mock hadde breaking changes ved major oppdatering som gjorde at personopplysninger ikke ville kjøre igang lokalt. Fikser ved å endre mocking av data og auth.
Testes i dev
> Fikser feil ved start lokalt

- package-lock.json
- package.json
Oppdatert office info dependencies
Har testet selv i dev
> Oppdatert office reception info til 1.2.0 i dependencies

- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
- src/pages/forside/sections/6-flere-opplysninger/LenkerData.ts
Endret lenke til pensjonsopptjening
Har testet selv i dev
> Endret lenke til pensjonsopptjening i prod og dev

- src/utils/redirects.ts
Fjerner ubrukte redirects og bruk av "kontaktadresse" som ikke lenger er mulig å endre i Personopplysninger.
Testet i dev
> Fjerner referanser til å endre kontaktadresse

- src/pages/endre-kontonummer/EndreKontonummer.tsx
- src/text/en.ts
- src/text/nb.ts
- src/text/nn.ts
- Endret teksten
- Endret URL til å peke på bokmål, nynorsk og engelsk-sider
- Endret rekkefølge slik at Endre knappen vises over info-boksen
Er blitt testet i dev
> Endret tekst, URL og rekkefølge av komponenter i endring av kontonummer

- src/text/en.ts
- src/text/en/information.ts
- src/text/nb.ts
- src/text/nb/informasjon.ts
- src/text/nn.ts
- src/text/nn/informasjon.ts
- **Tekst enderinger**
- **Tekst Endringer seccond try**
> Tekst endringer 2nd try

- .github/workflows/build-and-deploy-intern.yml
- .github/workflows/deploy.prod.intern.yml
- .nais/intern/config.yml
- .nais/intern/vars-prod.yml
Lagt til workflows slik at appen midlertidig kan bli deployet til en intern ingress i prod. Dette gjør det enklere å teste endringer i de nye backend appene.
Intern URL: https://www.intern.nav.no/person/personopplysninger
Har testet selv i dev / prod
> Deploy til intern ingress
